    name: Sync Fork

    on:
      schedule:
        - cron: '0 * * * *' 
      workflow_dispatch: # 允许手动触发

    jobs:
      sync:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout your fork
            uses: actions/checkout@v4
            with:
              fetch-depth: 0 # 获取完整历史，避免合并冲突

          - name: Sync fork
            uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
            with:
              upstream_sync_repo: 'fanhao375/microduck-replica-cad'
              upstream_sync_branch: 'master'
              target_sync_branch: 'mastr'
              git_push_args: --force
              git_pull_args: --ff-only
    
